spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydatabase
    username: user
    password: password
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka
